// Provisioning sketch — flash ONCE to write HMAC key into EEPROM.
// After flashing, replace with PasskeyLock.ino for normal operation.
//
// Usage:
//   1. Paste your 64-char hex secret from the web portal below.
//   2. Flash to the Nano.
//   3. Open Serial Monitor (115200). You should see "Key written OK."
//   4. Flash PasskeyLock.ino. The key persists in EEPROM.

#include <EEPROM.h>

// Replace with the secret generated by the web portal (64 hex chars = 32 bytes)
static const char SECRET_HEX[] = "0000000000000000000000000000000000000000000000000000000000000000";

static const uint16_t EEPROM_ADDR = 0;  // Start address for the 32-byte key

void setup() {
    Serial.begin(115200);
    while (!Serial) {}

    if (strlen(SECRET_HEX) != 64) {
        Serial.println("ERROR: SECRET_HEX must be exactly 64 hex characters (32 bytes).");
        return;
    }

    for (uint8_t i = 0; i < 32; i++) {
        char byteStr[3] = { SECRET_HEX[i * 2], SECRET_HEX[i * 2 + 1], '\0' };
        uint8_t val = (uint8_t)strtol(byteStr, nullptr, 16);
        EEPROM.update(EEPROM_ADDR + i, val);
    }

    // Verify readback
    bool ok = true;
    for (uint8_t i = 0; i < 32; i++) {
        char byteStr[3] = { SECRET_HEX[i * 2], SECRET_HEX[i * 2 + 1], '\0' };
        if (EEPROM.read(EEPROM_ADDR + i) != (uint8_t)strtol(byteStr, nullptr, 16)) {
            ok = false;
            break;
        }
    }

    Serial.println(ok ? "Key written OK. Flash PasskeyLock.ino now." : "ERROR: Readback mismatch!");
}

void loop() {}
